export const LOG_OUT = 'APP/LOG_OUT'
export const SIGN_IN = 'APP/SIGN_IN'

export const CREATE_TEST = 'TEST/CREATE_TEST'
export const DELETE_TEST = 'TEST/DELETE_TEST'
export const CHANGE_VISIBILITY = 'TEST/CHANGE_VISIBILITY'

export const GET_USER_STATISTICS = 'STATISTIC/GET_USER_STATISTICS'
export const GET_TEST_STATISTICS = 'STATISTIC/GET_TEST_STATISTICS'
export const GET_USER_TEST_STATISTICS = 'STATISTIC/GET_USER_TEST_STATISTICS'
export const GET_ALL_STATISTICS = 'STATISTIC/GET_ALL_STATISTICS'